### ISSUE TITLE
Make it template

### ISSUE THREAD

**Issue by amitkr-codes** [ProgrammingError/ultroid-cred-example#3]
Make it template and add `https://github.com/TechiError/ultroid-cred-example/generate` in readme so that we get option to generate this repo as public or private.

**Comment by New-dev0** [comment]
Nice

**Comment by ghost** [comment]
Good Idea

**Comment by TechiError** [comment]
> Make it template and add `https://github.com/TechiError/ultroid-cred-example/generate` in readme so that we get option to generate this repo as public or private.

Done
